name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
              ec2-user@3.107.164.86 << 'EOF'
          set -e
          cd /var/www/html  # Ganti dengan direktori yang sesuai dengan setupmu
          sudo git fetch origin
          sudo git reset --hard origin/main
          sudo chown -R ec2-user:nginx /var/www/html/  # Sesuaikan dengan user dan group yang digunakan
          sudo chmod -R 775 /var/www/html/  # Sesuaikan dengan izin yang kamu inginkan
          sudo systemctl reload nginx
          echo "Deployment successful!"
          EOF
